[package]
name = "otr"
version = "0.1.1"
edition = "2021"
authors = [ "Michael Picht <mipi@fsfe.org>"]
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
base64 = "0.13"
blowfish = "0.8"
block-modes = "0.8"
chrono = "0.4"
dirs = "4"
hex = "0.4"
itertools = "0.10" 
md-5 = "0.10"
once_cell = "1"
quick-xml = { version = "0.22", features = [ "serialize" ] }
rand = "0.8"
random-string = "1"
rayon = "1.5"
regex = "1"
reqwest = { version = "0.11", features = ["blocking"] }
rust-ini = "0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.3"
