[package]
name = "otr"
version = "0.6.1"
description = "otr decodes and cuts video files that were downloaded from Online TV Recorder <https://onlinetvrecorder.com/>"
edition = "2021"
authors = [ "Michael Picht <mipi@fsfe.org>"]
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
base64 = "0.21"
blowfish = "0.8"
block-modes = "0.8"
chrono = "0.4"
clap = { version = "4", features = [ "derive" ] }
dirs = "5"
hex = "0.4"
indoc = "2"
itertools = "0.12" 
lazy_static = "1" 
md-5 = "0.10"
once_cell = "1"
quick-xml = { version = "0.31", features = [ "serialize" ] }
rand = "0.8"
random-string = "1"
rayon = "1"
regex = "1"
reqwest = { version = "0.11", features = ["blocking"] }
rust-ini = "0.20"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
